version: "3.9"
services:
  triton:
    image: nvcr.io/nvidia/tritonserver:20.12-py3
    command: tritonserver --model-repository=/models
    shm_size: '2gb'
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./models_repository:/models
    runtime: nvidia
  web:
    build: app
    ports:
      - "80:80"
    volumes:
      - ./data/sqlite.db:/sqlite.db
    runtime: nvidia
#  telegram:
#    build: telegram
#    runtime: nvidia
